name: Format with PHP CS Fixer

on: [pull_request]

jobs:
  php-cs-fixer:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: zip, mysql, gd
          coverage: none
        env:
          runner: self-hosted

      - name: Run PHP CS Fixer
        run: composer run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
