name: Format with PHP CS Fixer

# will only trigger when creating a pull request event to any branch
on: [pull_request, push]

jobs:
  php-cs-fixer:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          node-version: 16

      # we need to install the vendor packages as php fixer for this project
      # is configured under netsells vendor
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Run PHP CS Fixer
        run: composer run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply PHP CS Fixer Changes

